version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-nutritional
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME_LOCAL}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD_LOCAL}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME_LOCAL}
    env_file:
      - .env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo: